apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zc887lnv4-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zc887lnv4-java-springboot-gitops